# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6f628e7a896bd2b606c50073a7c0cf8837a898c2e27130b79a3792d3da13f6dd86a8a3fdabe15a9d603595cf6a6635bd629309634b63bdb22191cd49e0e0e53

test:
  secret_key_base: 01ef5736a0b4c3a876bfb1598539eaf7f18d5db3ee79f85eb9badf8edb672692e5b914848ebe565b216bff7999f9a7ccf475f3bf25288dd40295740748b333f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
